/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
/*plane.h*/

#include "math.h"

#ifndef _PLANE_H_
#define _PLANE_H_

class Plane {
public:
  Plane(); //constructor
  ~Plane(); //deconstructor

//construct plane with args
Plane(vec3 _va, vec3 _vb, vec3 _vc, vec3 _norm) : _va ( vA ), _vb ( vB ), _vc ( vC ), _norm ( normal );

   const vec3 vA;
   const vec3 vB;
   const vec3 vC;

   const vec3 normal;

  //points are deduceable
   auto points[4];

  /*get the plane vectors*/
  //this returns one
   const vec3& getVector(vec3& v){
     return v;
   }


  //return a normal for the plane
  const vec3& getNormal(vec3& n){
    return n;
  }

  //returns a point on the plane
  const auto& getPoint(auto& p){
    return p;
  }

  //returns a plane
  const Plane& getPlane(Plane& p){
    return p;
  }
  

};


#endif
