/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
/*iglobals.h*/

#ifndef _I_GLOBALS_H_
#define _I_GLOBALS_H_

#include "iwidget.h"

#define COLOR_SEL_BRUSHES 00xFF001

class QESGlobals {
public:
  //constructor
  QESGlobals();
  ~QESGlobals();//deconstructor

  //global widgets
  QWidget* d_MainWindow;
  QWidget* d_ToolBar;// ESMatic 1.0, doesn't have a toolbar, this ESMatic app does
  QWidget* d_XYWindow;
  QWidget* d_XZWindow;
  QWidget* d_YZWindow;
  QWidget* d_GlBase;
  QWidget* d_GlRectangle;// gl window?
  QMenu* d_MainMenu;// File

  //global variables

  bool m_bBrushSelMode; // is brush selected
  bool m_bMdlSelMode; // model is selected

  int m_nGlobalsEntityList; // make a class of this soon

  float d_grid_celi;
  float d_grid_floor;
  float d_grid_scale; // grid size

  bool m_bAutoCaulk; // do brushes automatically caulk on creation
};

#endif
